name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build-deps-apt
      run: |
        dependencies="flex build-essential gcc git libboost-dev libboost-regex-dev libgmp-dev libmpfr-dev libmpc-dev"
        sudo apt install -y $dependencies
    - name: build-dep-cc65
      run: |
        cc_version=2.19
        curl -L https://github.com/cc65/cc65/archive/refs/tags/V$cc_version.tar.gz | tar xz
        mv cc65-$cc_version cc65
        cd cc65/
        make # May fail with "-j" because conflicting temporary files
    - name: build-gcc
      run: FORCE_INSTALLS=1 CC65_PATH=$(pwd)/cc65/bin ./build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: gcc-6502
        path: prefix/bin/*
